title: Tech-Law-Deadlines
description: Countdowns to {Law} + {AI, Privacy, Security, IP} conference, workshop, and symposia deadlines.
author: Nathan Reitinger

domain: "tech-law-deadlines.github.io"
baseurl: ""

github_username: tech-law-deadlines
github_repo: tech-law-deadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
