title: Tech-Law-Deadlines
description: Countdowns to top LAW + {AI, Privacy, Security, IP} conference, workshop, symposia deadlines.
author: Nathan Reitinger

domain: "tech-law-deadlines.github.io"
baseurl: ""

github_username: tech-law-deadlines
github_repo: tech-law-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
